train:
  rgb_static:
    - _target_: torchvision.transforms.Resize
      size: 224
    - _target_: calvin_agent.utils.transforms.ScaleImageTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]
    - _target_: calvin_agent.utils.transforms.AddGaussianNoise
      mean: [0.0]
      std: [0.01]
  rgb_gripper:
    - _target_: torchvision.transforms.Resize
      size: 224
    - _target_: calvin_agent.utils.transforms.ScaleImageTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]
    - _target_: calvin_agent.utils.transforms.AddGaussianNoise
      mean: [0.0]
      std: [0.01]

    - _target_: torchvision.transforms.Resize
      size: 64
    - _target_: torchvision.transforms.Normalize
      mean: [0.1,]
      std: [0.2,]
    - _target_: calvin_agent.utils.transforms.AddGaussianNoise
      mean: [ 0.0 ]
      std: [ 0.01 ]
  robot_obs:
    - _target_: calvin_agent.utils.transforms.NormalizeVector
      mean: [0.039233, -0.118554,  0.507826,  1.079174, -0.083069,  1.579753, 0.095367]
      std: [0.150769, 0.1104  , 0.06253 , 2.883517, 0.126405, 0.377196, 0.995442]
    - _target_: calvin_agent.utils.transforms.AddGaussianNoise
      mean: [0.0]
      std: [1]

val:
  rgb_static:
    - _target_: torchvision.transforms.Resize
      size: 224
    - _target_: calvin_agent.utils.transforms.ScaleImageTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]
  rgb_gripper:
    - _target_: torchvision.transforms.Resize
      size: 224
    - _target_: calvin_agent.utils.transforms.ScaleImageTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]

    - _target_: torchvision.transforms.Resize
      size: 64
    - _target_: torchvision.transforms.Normalize
      mean: [0.1,]
      std: [0.2,]
  robot_obs:
    - _target_: calvin_agent.utils.transforms.NormalizeVector
      mean: [0.039233, -0.118554,  0.507826,  1.079174, -0.083069,  1.579753, 0.095367]
      std: [0.150769, 0.1104  , 0.06253 , 2.883517, 0.126405, 0.377196, 0.995442]
    - _target_: calvin_agent.utils.transforms.AddGaussianNoise
      mean: [0.0]
      std: [1]
